# Generated by Django 5.2.15 on 2026-07-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_patient_checked_in_at_and_more'),
        ('doctors', '0002_doctor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorQueueState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('queue_started_at', models.DateTimeField(blank=True, help_text="When the doctor began the day's first consultation.", null=True)),
                ('current_delay_minutes', models.IntegerField(default=0, help_text='Signed minutes behind (>0) or ahead (<0) of schedule.')),
                ('estimated_finish_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_appointment', models.ForeignKey(blank=True, help_text='Consultation currently in progress, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_states', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-date', 'doctor_id'],
                'indexes': [models.Index(fields=['doctor', 'date'], name='queues_doct_doctor__2b2b28_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='unique_queue_state_per_doctor_day')],
            },
        ),
    ]
