# Generated by Django 5.2.15 on 2026-07-06 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_doctor_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('offered_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['doctor', 'date', 'status'], name='appointment_doctor__37fecf_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_e9cb17_idx'), models.Index(fields=['status', 'expires_at'], name='appointment_status_aa2c25_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'offered'])), fields=('patient', 'doctor', 'date'), name='unique_active_waitlist_entry')],
            },
        ),
    ]
