# Generated by Django 5.2.15 on 2026-07-06 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_waitlistentry'),
        ('doctors', '0002_doctor_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_duration', models.PositiveIntegerField(help_text='Minutes')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=30, help_text='Predicted consultation length in minutes'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='offered_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.visittype'),
        ),
        migrations.CreateModel(
            name='AppointmentDurationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_minutes', models.PositiveIntegerField()),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.8)),
                ('prediction_source', models.CharField(choices=[('rule_based', 'Rule Based'), ('ml', 'Ml'), ('manual', 'Manual')], default='rule_based', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duration_prediction', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_predictions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_predictions', to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duration_predictions', to='appointments.visittype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'visit_type'], name='appointment_doctor__ef9515_idx')],
            },
        ),
    ]
