# Generated by Django 5.2.15 on 2026-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_visittype_appointment_actual_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
