# Generated by Django 5.2.15 on 2026-07-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_attendance_status_and_more'),
        ('doctors', '0002_doctor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDayBookingLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_locks', to='doctors.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_day_booking_lock')],
            },
        ),
    ]
